### Create watchlist request
POST http://localhost:8000/watchlists/watchlis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImM4ODQyOWI1LTI1ODktNDM2OS04ZGEzLTAxZDNmYzZiNzlmOSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiZXhwIjoxNjg0MzI4NTE1LCJpc3MiOiJXYXRjaHdpc2UiLCJhdWQiOiJXYXRjaHdpc2UifQ.pITkNOAO2STiOxNCoP11rdaLZ0Ss5xxuW_cMcxmgo-0 

### Get all watchlists
GET http://localhost:8000/watchlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImM4ODQyOWI1LTI1ODktNDM2OS04ZGEzLTAxZDNmYzZiNzlmOSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiZXhwIjoxNjg0MzI4NjQyLCJpc3MiOiJXYXRjaHdpc2UiLCJhdWQiOiJXYXRjaHdpc2UifQ.6eBg4SpKRkHifvFcxvRuPuMcHqSenF5pzaw7f8sVQ2w

### Add movie to watchlist
POST http://localhost:8000/watchlists/64637d68503ebe2260b742e1/movie/60410
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImI4MTJkNDU3LWUzZDQtNDMxNy05ZDdmLTc0M2ZmZjc3ODE2NCIsImVtYWlsIjoiaWx5YTMwMDRAZ21haWwuY29tIiwiZXhwIjoxNjg0MjQ2MjM4LCJpc3MiOiJXYXRjaHdpc2UiLCJhdWQiOiJXYXRjaHdpc2UifQ.hIlFFc9ZzmDsyJxO-yLN-3dLveuOK8bIaf6hz3CSHu8

### Remove movie from watchlist
DELETE http://localhost:8000/watchlists/64637d68503ebe2260b742e1/movie/60410
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImI4MTJkNDU3LWUzZDQtNDMxNy05ZDdmLTc0M2ZmZjc3ODE2NCIsImVtYWlsIjoiaWx5YTMwMDRAZ21haWwuY29tIiwiZXhwIjoxNjg0MjQ2MjM4LCJpc3MiOiJXYXRjaHdpc2UiLCJhdWQiOiJXYXRjaHdpc2UifQ.hIlFFc9ZzmDsyJxO-yLN-3dLveuOK8bIaf6hz3CSHu8

### Remove movie from watchlist
DELETE http://localhost:5178/watchlists/648e2a76c773f57e0abc450c/movie/335984
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ijg5YjRmNDU3LTIzNzktNDNkNS04YjNlLTdkNGMzOGZmODM4MCIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiZXhwIjoxNjg3MDk0OTI1LCJpc3MiOiJXYXRjaHdpc2UiLCJhdWQiOiJXYXRjaHdpc2UifQ.ZRikLS0ausrVi5OnHj4ZP673tUmG0vI1A_sPd1JCkOo