version: '3.9'

networks:
  dev:
    driver: bridge

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - dev

  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ilya3004
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userdb
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./UserService/dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev

  watchlist-service-db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev

  user-service:
    image: docker.io/ilya3004/user-service
    depends_on:
      - rabbitmq
      - user-service-db
    container_name: user-service-services
    ports:
      - "8080:80"
    build:
      context: UserService
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=user-service-db;Port=5432;Database=userdb;User ID=postgres;Password=ilya3004;
      - JwtSettings__Secret=super-secret-key
      - JwtSettings__ExpiryMinutes=60
      - JwtSettings__Issuer=Watchwise
      - JwtSettings__Audience=Watchwise
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  watchlist-service:
    image: docker.io/ilya3004/watchlist-service
    depends_on:
      - rabbitmq
      - watchlist-service-db
    container_name: watchlist-service-services
    ports:
      - "8181:81"
    build:
      context: WatchlistService
      dockerfile: Dockerfile
    environment:
      - DatabaseSettings__ConnectionString=mongodb://mongo_db:27017
      - DatabaseSettings__DatabaseName=WatchlistDB
      - DatabaseSettings__CollectionName=Watchlists
      - ASPNETCORE_URLS=http://+:81
    networks:
      - dev

volumes:
  postgres-data:
  mongodb_data:
  rabbitmq_data:
